### ISSUE TITLE
Job details are never deleted

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/osmium#14]
The XenonManager.jobs instance variable gets a new SandboxedJob for each job submitted. In small scenarios this is no problem, but for a server, every job will keep adding to memory and slow down lookup times.

I can think of two mechanisms for removing jobs:

1. a HTTP DELETE statement from the client to cancel a job if needed and remove it from memory
2. a timeout after which a finished or cancelled job gets deleted.

**Comment by sverhoeven** [comment]
Option 2 is already implemented using the deleteTimeout config option. See https://github.com/NLeSC/osmium/blob/master/src/main/java/nl/esciencecenter/osmium/job/JobsPoller.java#L112
